name: aniwatch
description: A sample command-line application.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.0-42.1.beta

# Add regular dependencies here.
dependencies:
 dio: 
 encrypt:
 html:
 isar:
 tokuwari_models:
  git:
    url: https://github.com/femalemonkeyman/tokuwari-models
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
